// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzfjujnscwwoiwfnaaxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6Zmp1am5zY3d3b2l3Zm5hYXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NDU0NzIsImV4cCI6MjA1NjEyMTQ3Mn0.UgSAUofwhJqME21U86tyAsA7_t-aOKj32eDtxZ3nUJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);